### ISSUE TITLE
multiple TXT records should not always be concatenated.

### ISSUE THREAD

**Issue by janderholm** [tailhook/dns-parser#29]
This library concatenates all strings in a TXT record. Many (probably most) applications treat the records individually.

See for example:
http://www.zeroconf.org/rendezvous/txtrecords.html

The thing with concatenating TXT records seem to come from some weird email RFC (SPF?) but I can't find anything about it in the more generic mdns RFCs. Anyway I think it is better to let applications interpret the records themselves.

**Comment by tailhook** [comment]
Have you seen this issue on the real data? I think the mistake of the current implementation is that it assumes that multiple records can be present in a single answer (i.e. single RRData). I hardly remember that I've investigated that an reached a conclusion that it should not be possible. So while current implementation is inefficient and doesn't handle non-utf8 data it should handle two records easily. I mean two records are present as a separate entries in `answers` vector.

But, I have to study the RFC again to be sure :)

I.e. I think we need to change `txt::Record` to `struct Record<'a>(pub &'a [u8])` (because TXT records are actually binary).

**Comment by janderholm** [comment]
I have seen it. Currently I'm parsing data coming from video surveillance cameras (of the brand Axis) and they sometimes have multiple fields in one record. Also rendezvous is Apples implementation of mdns/zeroconf/bonjour/whatever and since they make it very easy to create several fields in a record I think chances are there many apple devices and applications that might have it as well. I don't have any apple devices though so I can't test it.

You can look up mDNSResponderPosix if you want to try it out. It's fairly well used in devices such as routers and other IOT devices to provide Zeroconf services and is simple to configure.

I think a Vec<[u8]> is better. The record is supposed to contain 1 or more 1 byte length delimited strings. I.e. they look like this (although they may contain any binary data):

    -------------------------------------------------------------------
    | 0x0A | name=value | 0x08 | paper=A4 | 0x12 | Rendezvous Is Cool |
    -------------------------------------------------------------------

This is the section in RFC 1035:

    3.3.14. TXT RDATA format
    
        +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
        /                   TXT-DATA                    /
        +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+

    where:
    
    TXT-DATA        One or more <character-string>s.
    
    TXT RRs are used to hold descriptive text.  The semantics of the text
    depends on the domain where it is found.

The key is:

    One or more <character-string>s.

And on page 12:

    <character-string> is a single
    length octet followed by that number of characters.  <character-string>
    is treated as binary information, and can be up to 256 characters in
    length (including the length octet).

**Comment by tailhook** [comment]
Okay, you're right, sorry for confusion.
